Move blog app into apps
djangocameroon/website_api pull request #35
Opened 2024-09-27 03:57 UTC by JohananOppongAmoateng

Closes #25 
This pull request is a continuation of the work  of @saahndongransom on the blog app. I refactored the code and moved the blog app from the root directory into the apps folder then made the needed changes in the settings and urls.

2024-10-04 05:25 UTC, yokwejuste requested changes
Please can you have a look at the changes mentioned in this review?

2024-10-04 05:25 UTC, yokwejuste commented on apps/blog/models/blog.py
> +class Blog(models.Model):
What we need now here is a uuid for the primary key
```python
from apps.users.models.base_model import BaseModel


class Blog(BaseModel):
```

After that please proceed to `makemigrations` command.

2024-10-04 05:25 UTC, yokwejuste commented on apps/blog/models/image.py
> +class Image(models.Model):
Same for images too:
```python
from apps.users.models.base_model import BaseModel


class Image(BaseModel):
```

2024-10-04 05:25 UTC, yokwejuste commented on apps/blog/models/author.py
> +class Author(models.Model):
Same for authors too:

```python
from apps.users.models.base_model import BaseModel


class Author(BaseModel):
```

2024-10-04 05:25 UTC, yokwejuste commented on apps/blog/serializers/image_serializer.py
> +        fields = '__all__'
Name the fields here please, it is always good practice to list the field and declare as read only the ones not necessary or required during post or put requests.

```python

# ....
fields = [ 'all', 'the', 'fields', 'name',]

2024-10-04 05:25 UTC, yokwejuste commented on apps/blog/serializers/tag_serializer.py
> +        fields = '__all__'
Same here about the fields

2024-10-04 05:39 UTC, JohananOppongAmoateng commented on apps/blog/serializers/tag_serializer.py
> +        fields = '__all__'
Noted will push the necessary changes

2024-10-05 17:20 UTC, yokwejuste approved these changes
🐒  LGTM

2024-10-05 17:21 UTC, merged